//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Temperatures = new HashSet<Temperature>();
            this.UserDetails = new HashSet<UserDetail>();
            this.HeartRates = new HashSet<HeartRate>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string pwdHash { get; set; }
        public int UserType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Temperature> Temperatures { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<HeartRate> HeartRates { get; set; }
    }
}
